# Generated by Django 3.2.5 on 2021-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_alter_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название статуса'),
        ),
    ]
