# Generated by Django 3.2.5 on 2021-07-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0005_service_status_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/', verbose_name='file')),
                ('export_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
